### ISSUE TITLE
Develop a basic web application using framework of choice

### ISSUE THREAD

**Issue by kristiandiana** [DSC-McMaster-U/Ocular-Disease-Identifier#5]
Task: Select a framework to develop our frontend on (I suggest React, because I have experience with it, but it is really up to you guys and your interests!). Setup the web app to be able to use CSS framework of choice (I suggest Tailwind, but once again whatever you guys think is best). All work to be done in the frontend directory!

Completion Requirements: Have a single page for now, and you should be able to upload image files and display a "preview" of the uploaded image on the page.

Comments: Don't worry too much about the styling just yet, we have plenty of time to make it look pretty later. We just want to get the basic functionality solidified first! If you have time, maybe begin planning a general layout of how you think the web page should look (If you want to use Figma that's great!).

**Comment by jayendranar02** [comment]
hello I am in the chat just because there is a project given to me by my college, they told to solve an application based issue for any github repos.... pls help and respond to my request.... you just have to comment below and accept what i am contributing

**Comment by jayendranar02** [comment]
Step-by-Step Setup
1.	Create React App
First, ensure you have Node.js and npm installed. Then, create a new React application:
bash
Copy code
npx create-react-app frontend
cd frontend
2.	Install Tailwind CSS
Follow the steps to install Tailwind CSS in your React application.
o	Install Tailwind CSS and its dependencies:
bash
Copy code
npm install -D tailwindcss postcss autoprefixer
o	Initialize Tailwind CSS:
bash
Copy code
npx tailwindcss init -p
This creates a tailwind.config.js and a postcss.config.js file.
o	Configure Tailwind:
Open tailwind.config.js and set the content paths:
javascript
Copy code
/** @type {import('tailwindcss').Config} */
module.exports = {
    content: [
        "./src/**/*.{js,jsx,ts,tsx}",
    ],
    theme: {
        extend: {},
    },
    plugins: [],
}
o	Add Tailwind to your CSS:
Open src/index.css and replace its content with:
css
Copy code
@tailwind base;
@tailwind components;
@tailwind utilities;
3.	Create Image Upload Component
Create a new component to handle image uploads. Create a new file at src/ImageUpload.tsx:
tsx
Copy code
// src/ImageUpload.tsx

import React, { useState } from 'react';

const ImageUpload: React.FC = () => {
    const [selectedImage, setSelectedImage] = useState<File | null>(null);
    const [imagePreviewUrl, setImagePreviewUrl] = useState<string | null>(null);

    const handleImageChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        if (event.target.files && event.target.files[0]) {
            const file = event.target.files[0];
            setSelectedImage(file);

            const reader = new FileReader();
            reader.onloadend = () => {
                setImagePreviewUrl(reader.result as string);
            };
            reader.readAsDataURL(file);
        }
    };

    return (
        <div className="flex flex-col items-center justify-center h-screen bg-gray-100">
            <input
                type="file"
                accept="image/*"
                onChange={handleImageChange}
                className="mb-4 p-2 border border-gray-300 rounded"
            />
            {imagePreviewUrl && (
                <img
                    src={imagePreviewUrl}
                    alt="Preview"
                    className="w-64 h-64 object-cover border rounded"
                />
            )}
        </div>
    );
};

export default ImageUpload;
4.	Use the Image Upload Component
Open src/App.tsx and modify it to use the ImageUpload component:
tsx
Copy code
// src/App.tsx

import React from 'react';
import './index.css'; // Ensure Tailwind is included
import ImageUpload from './ImageUpload';

const App: React.FC = () => {
    return (
        <div className="App">
            <h1 className="text-3xl text-center mt-10">Image Upload Preview</h1>
            <ImageUpload />
        </div>
    );
};

export default App;
5.	Run the Application
Start the development server:
bash
Copy code
npm start
Open your browser and navigate to http://localhost:3000. You should see a page with an image upload field. After selecting an image file, you should see a preview of the uploaded image.
Next Steps
You now have a basic React application with Tailwind CSS that allows users to upload images and see a preview. Here are some potential next steps:
•	Add error handling: Implement checks for file size and type.
•	Implement image cropping: Allow users to crop images before uploading.
•	Backend integration: Set up a backend to handle file uploads if needed.
•	Styling improvements: Enhance the UI with more Tailwind styles.
